### ISSUE TITLE
Data loader should be updated to read HDF5 inputs

### ISSUE THREAD

**Issue by plstcharles** [mila-iqia/COVI-ML#1]
There's an open PR in the simulator ([here](https://github.com/mila-iqia/covi-simulator/pull/8)) that replaces the zip-of-a-thousand-pickles used as training data by an HDF5 archive. This archive contains a single dataset under the name `dataset` that is 3-dimensional with shape: `DAY x HOUR x HUMAN`. The dataset is automatically compressed via gzip.

The code required to read the dataset is something like:
```
import h5py
import pickle
with h5py.File(hdf5_path, 'r') as fd:
    dataset = fd['dataset']
    assert dataset.shape[0] == n_days
    assert dataset.shape[1] == 24
    assert dataset.shape[2] == n_people
    for day_idx, hour_idx, human_idx in <range of all samples>:
        sample_buffer = dataset[day_idx, hour_idx, human_idx]
        sample = pickle.loads(sample_buffer)
        ...
```
The samples should then be identical to what was being pickled before. I didn't have time to touch the code on this side to adapt these changes (don't quite know where to begin, truly), so... TODO.

**Comment by nasimrahaman** [comment]
Solved!
